---
- name: Deploy Web App
  hosts: web_servers
  gather_facts: true
  become: true

  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes