---
- name: Update and upgrade apt packages
  hosts: 10.0.9.8
  port: 1022
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
        autoclean: yes
        autoremove: yes